version: '3.3'

services:

   nginx:
     image: nginx:latest
     depends_on:
       - mysql
     links:
       - php
     volumes:
       - .:/code
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
     ports:
       - 80:80

   mysql:
     image: mysql:5.7
     volumes:
       - ./data:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=password
       - MYSQL_DATABASE=application
     ports:
       - 3306:3306

   php:
     image: php:7-fpm
     volumes:
       - .:/code
     ports:
       - 9000:9000
